count_1=int(input("Введите количество элементов 1 набора = "))
list_1=list(int(input(f" Введите {i} элемент 1 набора = ")) for i in range(count_1))
count_2=int(input("Введите количество элементов 2 набора = "))
list_2=list(int(input(f" Введите {i} элемент 2 набора = ")) for i in range(count_2))
print(list_1)
print(list_2)
list_1=set(list_1)
list_2=set(list_2)
new_list=list_1.intersection(list_2)
print(f"Результат = {sorted(new_list)}")
